nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Autoriser les CORS uniquement pour les routes commençant par /api/
            allow_origin: ['*']  # Remplacez '*' par l'origine autorisée si besoin (par exemple 'http://localhost:4200')
            allow_headers: ['Content-Type', 'Authorization']  # En-têtes autorisés
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # Méthodes HTTP autorisées
            allow_credentials: true  # Autoriser les informations d'identification (cookies, authentification)

