version: '4.38'

services:
  mysql:
    image: mysql:8.3
    container_name: symfony_mysql
    ports:
      - "3307:3306"  # Port 3307 sur l'hôte, mais la DB écoute sur 3306 dans le conteneur
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # ✅ Autorise un root sans mot de passe
      MYSQL_DATABASE: my_project
      MYSQL_USER: symfony_user  # Ajout d'un utilisateur personnalisé
      MYSQL_PASSWORD: symfony_password  # Mot de passe pour l'utilisateur
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - defi_symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # PhpMyAdmin accessible sur http://localhost:8081
    environment:
      PMA_HOST: mysql  # Correspond au nom du service MySQL
      PMA_PORT: 3306
      PMA_USER: symfony_user  # L'utilisateur défini dans le service MySQL
      PMA_PASSWORD: symfony_password  # Le mot de passe défini dans le service MySQL
    depends_on:
      - mysql
    networks:
      - defi_symfony_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"  # Jenkins sera accessible sur http://localhost:9090
      - "50000:50000" # Utilisé pour les agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Pour stocker les configurations et jobs de Jenkins
    networks:
      - defi_symfony_network
    environment:
      JENKINS_OPTS: "--httpPort=8080"  # Choisir le port sur lequel Jenkins va tourner
    restart: unless-stopped  # Redémarre Jenkins en cas d'échec

networks:
  defi_symfony_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  jenkins_home:
    driver: local
