version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: symfony_mysql
    ports:
      - "3307:3306"  # Port 3307 sur l'hôte, mais la DB écoute sur 3306 dans le conteneur
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # ✅ Autorise un root sans mot de passe
      MYSQL_DATABASE: my_project
      MYSQL_USER: symfony_user  # Ajout d'un utilisateur personnalisé
      MYSQL_PASSWORD: symfony_password  # Mot de passe pour l'utilisateur
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - defi_symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # PhpMyAdmin accessible sur http://localhost:8081
    environment:
      PMA_HOST: mysql  # Correspond au nom du service MySQL
      PMA_PORT: 3306
      PMA_USER: symfony_user  # L'utilisateur défini dans le service MySQL
      PMA_PASSWORD: symfony_password  # Le mot de passe défini dans le service MySQL
    depends_on:
      - mysql
    networks:
      - defi_symfony_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true  # Nécessaire pour Docker-in-Docker
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Permet à Jenkins de communiquer avec Docker sur l'hôte
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      DOCKER_TLS_CERTDIR: ""  # Désactive la sécurité TLS (si nécessaire)
    networks:
      - defi_symfony_network
    # Ajout de la partie suivante pour installer Docker dans le conteneur Jenkins
    build:
      context: .
      dockerfile: Dockerfile.jenkins


networks:
  defi_symfony_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  jenkins_home:
    driver: local
