services:
  php:
    image: php:8.3-fpm
    container_name: symfony_php
    volumes:
      - C:/Users/33753/Desktop/Projet_finale/Defi:/var/www/html  # Assure-toi de partager le répertoire public
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
    - C:/Users/33753/Desktop/Projet_finale/Defi/public:/var/www/html/public # Assure-toi de partager le répertoire public
    - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Assure-toi que ce fichier est bien configuré
    depends_on:
      - php  
    networks:
      - symfony_network

  mysql:  # 👈 Assure-toi que le bon service est utilisé ici
    image: mysql:8.3  # 👈 Vérifie qu'il y a bien "image:"
    container_name: symfony_mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # ✅ Autorise un root sans mot de passe
        MYSQL_DATABASE: my_project            # 📌 Crée une base de données "symfony"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
